### ISSUE TITLE
project_viral_glycoprotein-pjvirgly

### ISSUE THREAD

**Issue by masterLZ** [opengl106/UCAS-assignments#13]
有能耐别删库。https://github.com/newypei/project_viral_glycoprotein-pjvirgly，链接在这里。垃圾

**Comment by gwsbhqt** [comment]
看了链接的repository也算开眼界了，这货的水平就这？就这还中国科学院大学？

**Comment by jasperzhong** [comment]
被fork了，洗不干净了，@opengl106 您自己删了也没用

**Comment by masterLZ** [comment]
> 被fork了，洗不干净了，@opengl106 您自己删了也没用
我fork了一份，但是想想觉得侮辱我的github，就留了一份在本地

**Comment by Shizuki-Kagurasaka** [comment]
真丢人
什么垃圾代码

**Comment by ChangJin0520** [comment]
偶吼，被 fork 了

**Comment by Shizuki-Kagurasaka** [comment]
上边的404
[https://github.com/Shizuki-Kagurasaka/project_viral_glycoprotein-pjvirgly](https://github.com/Shizuki-Kagurasaka/project_viral_glycoprotein-pjvirgly)
打算用这个小号来保存太君的大作了

**Comment by nepleo** [comment]
中科院 水平就这？？？？

**Comment by qeqeq1** [comment]
> 上边的404
> https://github.com/Shizuki-Kagurasaka/project_viral_glycoprotein-pjvirgly
> 打算用这个小号来保存太君的大作了

404的原因是github把链接在这里。垃圾当连接了=-=
