### ISSUE TITLE
季子越，你的日本天皇啥时候能带你去日本呢？

### ISSUE THREAD

**Issue by YouAreSpecialToMe** [opengl106/UCAS-assignments#17]
就这废物水平，还好意思写github？你这水平怕是去了你的帝国，连中学都毕业不了吧。你🐎biss。

**Comment by mobi12** [comment]
楼上太有趣了，竟然觉得这个东西是妈生的。妈生的物种会说这种话？

**Comment by 514DNA** [comment]
这个东西没🐎，这东西是撤硕里面的蛆成了精，晦气
