### ISSUE TITLE
太君，你今晚BISS，火葬场打算烤几分熟

### ISSUE THREAD

**Issue by 514DNA** [opengl106/UCAS-assignments#21]
不会有人用这东西的骨灰拌饭吧，不会吧，不会吧。那可是有够晦气的

**Comment by nepleo** [comment]
中科院学生的代码就这？？？？

**Comment by ESUAdmin** [comment]
给你来点劲爆的：

> 这些文件来源于巴拿马小型律所莫萨克-冯塞卡(Mossack Fonseca)，专长于为富人建立避税途径和秘密企业。文件的曝光令世界各地的政治领导人和其他实权人物深受打击。但人们认为它在中国特别敏感，因为共产党在习近平的领导下，誓言要从队伍中铲除腐败分子，希望给自己塑造一种平等的形象，尽管中国是世界上收入差距最明显的地方之一。
该组织本周三公布的资料涉及中共中央政治局常委，这个委员会由七名男性组成，是该国的权力中心。
订阅“简报”和“每日精选”新闻电邮
同意接收纽约时报中文网的产品和服务推广邮件
查看往期电邮 隐私权声明
报告显示，负责宣传工作的常委刘云山的儿媳是英属维尔京群岛注册的一家公司的股东和董事，而副总理张高丽的女婿，也在这个避税港拥有三家公司。
该报告列出的有亲戚控制离岸公司的常委中，第三个就是习近平。习近平的姐夫邓家贵和离岸公司的关系在2012年时就已经为人所知。当时，彭博新闻社(Bloomberg News)刊出了一篇关于习近平家族财富的文章，详细讲述了邓家贵及其妻齐桥桥的商业帝国。齐桥桥是习近平的姐姐。

巴拿马文件：

> 贾立青和她的丈夫背靠的是中国共产党最强大的两个机构。贾立青是中国前公安部部长、前最高人民检察院检察长贾春旺的女儿。刘乐飞的父亲则是中国宣传机构的负责人。上述消息来自专门报道亚洲银行业信息的网站金融亚洲(FinanceAsia)，以及与这对夫妇有交往的两名人士，他们选择匿名接受采访，以便维持这些关系。
