### ISSUE TITLE
大家冷静点，别给GitHub引流！！

### ISSUE THREAD

**Issue by Centauria** [opengl106/UCAS-assignments#22]
难道大家没发现Github渐渐的已经快连不上了吗
像这种危险的操作暴露给zf
只会增大gfw墙掉GitHub的可能性

建议截图传播完事，不要暴露地址

**Comment by logojackmowo-gh** [comment]
raw.githubusercontent.com已经不能直连了
而且轮子凭借着github不被墙的特性，在gh上传播自由门、无界浏览等轮子毒瘤，github不会仅仅因为这个被墙，gh要么配合中国监管，要么被墙

**Comment by ChChJJ** [comment]
> raw.githubusercontent.com已经不能直连了
> 而且轮子凭借着github不被墙的特性，在gh上传播自由门、无界浏览等轮子毒瘤，github不会仅仅因为这个被墙，gh要么配合中国监管，要么被墙

可以，我手机可以直连我把梯子关掉连给你看![Screenshot_20200719_231123_com.huawei.browser.jpg](https://user-images.githubusercontent.com/62100435/87878172-37f2bb80-ca15-11ea-986a-605ad1856520.jpg)![Screenshot_20200719_231135_com.quark.browser.jpg](https://user-images.githubusercontent.com/62100435/87878173-388b5200-ca15-11ea-88f8-1d10765bd511.jpg)

**Comment by ChChJJ** [comment]
> > raw.githubusercontent.com已经不能直连了
> > 而且轮子凭借着github不被墙的特性，在gh上传播自由门、无界浏览等轮子毒瘤，github不会仅仅因为这个被墙，gh要么配合中国监管，要么被墙
> 
> 可以，我手机可以直连我把梯子关掉连给你看第一个是华为自带的浏览器，第二个是夸克![Screenshot_20200719_231123_com.huawei.browser.jpg](https://user-images.githubusercontent.com/62100435/87878172-37f2bb80-ca15-11ea-986a-605ad1856520.jpg)![Screenshot_20200719_231135_com.quark.browser.jpg](https://user-images.githubusercontent.com/62100435/87878173-388b5200-ca15-11ea-88f8-1d10765bd511.jpg)

**Comment by ESUAdmin** [comment]
先帮各位大手子们引个流：

> 中共的这种雄心显然在全方位的彰显：在国内，微博、微信、微信公众号、抖音等社交媒体再次遭到“严打”，各种审查一而再再而三的“清洗”各个领域的不同的声音；随着疫情而出现的健康码成了堂而皇之的监控利器；“光盘行动”以及可能到来的数字货币和电子粮票让人胆战心惊。在香港，国安法的实行让中共对香港自由人士的逮捕肆无忌惮。在新疆，一刀切的全封闭的管理让民众苦不堪言，连基本医疗救治都无法保障。在内蒙古，政府强行以“第二类双语教育”的名义在内蒙古所有学校用汉语取代蒙语进行教学。在国际上，经过多年的韬光养晦，中共通过经济、商业、文化、学术等活动输出的价值观已经成为自由世界的威胁……虽是酷暑，但中共的升级版的宏图“一九八四”让人不寒而栗的
