### ISSUE TITLE
恁说“习近平病毒”没有歧视中国人和中共的意思，那恁说过的“支那人”“赵老爷”是什么意思？

### ISSUE THREAD

**Issue by logojackmowo-gh** [opengl106/UCAS-assignments#25]
![image](https://user-images.githubusercontent.com/65222482/85973551-a8ee1700-ba05-11ea-8417-ad205df9a83a.png)
![photo_2020-06-29_12-45-30](https://user-images.githubusercontent.com/65222482/85973791-7bee3400-ba06-11ea-9df4-cdfdd16c402a.jpg)
![photo_2020-06-29_12-45-34](https://user-images.githubusercontent.com/65222482/85973793-7d1f6100-ba06-11ea-831b-298807599f21.jpg)

**Comment by logojackmowo-gh** [comment]
季大佐删了不少推文，这些截图是我亲自截的，有备份的兄弟欢迎上传备份
（图1为今天凌晨大佐推特发布的内容，后来一瞬删除，archive备份: https://web.archive.org/web/20200628225456/https://twitter.com/opengl106/status/1277341181844893703 ）

**Comment by worm0527** [comment]
![image](https://user-images.githubusercontent.com/3963932/85977092-785eab00-ba0e-11ea-99e9-e285386f36f2.png)

**Comment by 514DNA** [comment]
鸡带佐给爷死就完事了

**Comment by mobi12** [comment]
这特么都叫政策不力，那美国那个叫什么？日本那个又改叫什么？毫无作为？真是马了隔壁的贱人
