### ISSUE TITLE
    1

### ISSUE THREAD

**Issue by imharryzhu** [opengl106/UCAS-assignments#29]

**Comment by kobayashmiyako** [comment]
可惜你连被中科大退学的资格都没有————根本考不上
还骂别人傻逼，真有趣

**Comment by imharryzhu** [comment]
> 可惜你连被中科大退学的资格都没有————根本考不上
> 还骂别人傻逼，真有趣

但凡有点水平也不会注册个小号在这叫嚣了

**Comment by cgoxopx** [comment]
> 可惜你连被中科大退学的资格都没有————根本考不上
> 还骂别人傻逼，真有趣

被中科大开除学籍的资格，恁野爹确实没有，不然指望恁去当太君干啥？

**Comment by yuliming1996** [comment]
应该是国科大-_-||

**Comment by yuliming1996** [comment]
国科大是科学院系统招本科生的大学

**Comment by imharryzhu** [comment]
它骂咱是支那，我们骂它傻逼有何不妥？

**Comment by DeepestAbyss** [comment]
> 可惜你连被中科大退学的资格都没有————根本考不上
> 还骂别人傻逼，真有趣

小林宫子，这又是哪位太君？
https://m.cmx.im/@kobayashmiyako/with_replies
https://twitter.com/kobayashmiyako/with_replies

![](https://i.postimg.cc/5ymSKtJf/EAe-A0-ZU4-AAUZoa.jpg)

![](https://i.postimg.cc/6qBdZNvg/EGNO2-L7-Ws-AEOeis.jpg)

![](https://i.postimg.cc/zfWWPfw4/EYTEGrr-Xg-AEf5zm.jpg)

**Comment by worm0527** [comment]
> 可惜你连被中科大退学的资格都没有————根本考不上
> 还骂别人傻逼，真有趣

太君是你吗🐶🐶🐶

**Comment by ESUAdmin** [comment]
> > 可惜你连被中科大退学的资格都没有————根本考不上
> > 还骂别人傻逼，真有趣
> 
> 小林宫子，这又是哪位太君？
> https://m.cmx.im/@kobayashmiyako/with_replies
> https://twitter.com/kobayashmiyako/with_replies
> 
> ![](https://camo.githubusercontent.com/cb970a099409f4587b8e49f828a014e14c57ba4e/68747470733a2f2f692e706f7374696d672e63632f35796d534b744a662f4541652d41302d5a55342d4141555a6f612e6a7067)
> 
> ![](https://camo.githubusercontent.com/47189d38e8685f56ce0adee9aa17fcc79d65afaa/68747470733a2f2f692e706f7374696d672e63632f367142645a4e76672f45474e4f322d4c372d57732d41454f6569732e6a7067)
> 
> ![](https://camo.githubusercontent.com/6f11db3802bcb2c0ac70c3f9216b5446847d00ef/68747470733a2f2f692e706f7374696d672e63632f7a665757506677342f455954454772722d58672d414566357a6d2e6a7067)

卧槽事创象出道大手子，恁真是太厉害啦！！！！！！！！111111111

给你鼓个掌

**Comment by ESUAdmin** [comment]
楼主上不了中科大就不要来黑屁别人，老老实实996
