### ISSUE TITLE
恭喜恭喜恭喜！！！

### ISSUE THREAD

**Issue by kikyous** [opengl106/UCAS-assignments#35]
恭喜恭喜恭喜！！！恭喜恭喜恭喜！！！恭喜恭喜恭喜！！！恭喜恭喜恭喜！！！恭喜恭喜恭喜！！！恭喜恭喜恭喜！！！恭喜恭喜恭喜！！！恭喜恭喜恭喜！！！恭喜恭喜恭喜！！！恭喜恭喜恭喜！！！恭喜恭喜恭喜！！！恭喜恭喜恭喜！！！恭喜恭喜恭喜！！！恭喜恭喜恭喜！！！恭喜恭喜恭喜！！！恭喜恭喜恭喜！！！恭喜恭喜恭喜！！！恭喜恭喜恭喜！！！恭喜恭喜恭喜！！！恭喜恭喜恭喜！！！恭喜恭喜恭喜！！！恭喜恭喜恭喜！！！恭喜恭喜恭喜！！！恭喜恭喜恭喜！！！恭喜恭喜恭喜！！！恭喜恭喜恭喜！！！恭喜恭喜恭喜！！！恭喜恭喜恭喜！！！

**Comment by xuchendev** [comment]
恭喜不用做作业了么
