### ISSUE TITLE
草，季大佐的垃圾代码竟然也进北极了

### ISSUE THREAD

**Issue by logojackmowo-gh** [opengl106/UCAS-assignments#41]
![截图0802133045](https://user-images.githubusercontent.com/65222482/89116264-7a5fd200-d4c4-11ea-8b02-52c00cf9fd17.jpeg)
真·遗臭千年

**Comment by ESUAdmin** [comment]
如果你早一点来送妈，那我相信恁全家的美丽户籍也会跟着进北极的。

这也算留存在世界历史的一部分了。

**Comment by logojackmowo-gh** [comment]
> 如果你早一点来送妈，那我相信恁全家的美丽户籍也会跟着进北极的。
> 
> 这也算留存在世界历史的一部分了。

![TIM图片20200813002108](https://user-images.githubusercontent.com/65222482/90040853-0f4fa000-dcfb-11ea-918f-a57b5c526eaf.jpg)

我反对季子越，恁可以出道我了。
中间的四位数你们ESU人完全有能力查，欢迎出道，欢迎橄榄

**Comment by logojackmowo-gh** [comment]
> 如果你早一点来送妈，那我相信恁全家的美丽户籍也会跟着进北极的。
> 
> 这也算留存在世界历史的一部分了。

如果您不是中国公民且您本人不在中国，您无法对我造成任何实际笋丝
如果您是中国公民或者您在中国或者都有，我可以一转报警
